### ISSUE TITLE
Hi  does you tool could unlock Vannlia Wow?

### ISSUE THREAD

**Issue by william19831103** [PolyFlower/NoNameUnlocker#4]
Hi  does you tool could unlock Vannlia Wow?

**Comment by PolyFlower** [comment]
Well it's not what you think it is. It's paid software from lua unlocker provider, without any obfuscation and etc. It does not have any actual payload, the payload itself is downloaded from their second server via tcp connection, when provided with correct authentication token, which is generated via packet exchange convo with second authentication server at start-up.
